apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-service-account
  namespace: docker-security
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-role
  namespace: docker-security
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-role-binding
  namespace: docker-security
subjects:
- kind: ServiceAccount
  name: app-service-account
  namespace: docker-security
roleRef:
  kind: Role
  name: app-role
  apiGroup: rbac.authorization.k8s.io